add branch max line numbers
System-Glitch/ESGILinter-C pull request #7
Opened 2018-11-22 16:16 UTC by Moussier

2018-11-22 17:34 UTC, System-Glitch requested changes

2018-11-22 17:34 UTC, System-Glitch commented on src/rules/max_line_numbers.c
> +  }
Why don't you just check `strlen` return value? This is unecessary processing.

2018-11-22 17:34 UTC, System-Glitch commented on src/rules/max_line_numbers.c
> +unsigned int max_line_numbers(arraylist_t *file, unsigned int n){
Use a more explicit name such as `check_max_line_length`.

2018-11-23 10:10 UTC, System-Glitch approved these changes

2018-12-03 09:58 UTC, WBPierre submitted a review, later dismissed
Need to change `arraylist_get(file, i);` to -> `get_line(file, i)`
You'll get a struct line_t like this :
`typedef struct line {
    char *line;
    char *source;
    int   start_line;
    int   end_line;
    int   real_line;
} line_t;`

2018-12-08 18:35 UTC, merged