add branch max file line numbers
System-Glitch/ESGILinter-C pull request #8
Opened 2018-11-22 16:18 UTC by Moussier

2018-11-22 17:44 UTC, System-Glitch requested changes

2018-11-22 17:44 UTC, System-Glitch commented on src/rules/max_file_line_numbers.c
> +    print_warning("fictive_file.c", n, arraylist_get(file, n), "Too much lines");
"Too **many** lines"
Also, it would be better to show the total amount of lines compared to the maximum instead of the line itself in this case.

2018-11-22 17:44 UTC, System-Glitch commented on src/test.c
> +
Memory leak, free the arraylist !!! ( `arraylist_free(file, 1)`)

2018-11-22 17:44 UTC, System-Glitch commented on src/test.c
> +
Memory leak, free the arraylist !!! ( arraylist_free(file, 1))

2018-12-03 09:55 UTC, WBPierre submitted a review, later dismissed
Need to change `arraylist_get(file, i);` to -> `get_line(file, i)`
You'll get a struct line_t like this :
`typedef struct line {
    char *line;
    char *source;
    int   start_line;
    int   end_line;
    int   real_line;
} line_t;`

2018-12-08 18:22 UTC, System-Glitch submitted a review, later dismissed

2018-12-08 18:23 UTC, merged